config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts

  root "posts#index"

  get '/about', to: 'pages#about'

  resources :charges, only: [:new, :create]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  def post_time_out
    create_date = created_at.to_date
    (create_date + 45.minutes - create_date).to_i
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :validate_invite, :on => :create
  attr_accessor :invite

  has_many :posts

  belongs_to :role
  before_create :set_default_role

  def validate_invite
    if self.invite != "destiny"
      self.errors[:base] << "The invite code you've entered is incorrect."
    end
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Help keep the Cayde-6 Project  - #{current_user.email}",
     currency: 'usd'
   )

   flash[:notice] = "Thanks for your support, #{current_user.email}! Feel free to support C6S again!"
   redirect_to user_path(current_user) # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Cayde-6 Sect Donation - #{current_user.email}",
      amount: Amount.default
    }
  end

  class Amount
    def self.default
      1000
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, :except => [:about]
  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :check_post_count, only: [:new, :create]
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Posted!"
      redirect_to posts_path
    else
      flash[:error] = "Not posted, try again!"
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    if @post.save
      flash[:notice] = "Updated!"
      redirect_to @post
    else
      flash[:error] = "Not updated, try again!"
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user == @post.user
      @post.destroy
      flash[:notice] = "Deleted your posting!"
      redirect_to posts_path
    else
      flash[:error] = "Posting not killed, try again!"
      redirect_to :back
    end
  end

  private

  def post_params
    params.require(:post).permit(:name, :console, :light_lvl, :activity, :destiny_class, :mic, :notes)
  end

  def check_post_count
    if current_user.posts.count >= 1
      redirect_to edit_post_path(current_user.posts.first),
        notice: 'You already have an active post.'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :invite)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<div class=post-wrap>
<%= form_tag charges_path do %>
  <h5>Click below to donate to Cayde-6 Sect and keep the site running!</h5>
  <div class="stripe-wrap">
    <script class='stripe-button' style='margin-left: 50%' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  </div>
<% end %>
  <h6>All donations are non-refundable</h6>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cayde6Sect</title>
  <meta name= "viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=PT+Sans' %>
  <%= stylesheet_link_tag 'application', 'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div>
  <nav class="navbar navbar-default navbar-relative-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= image_tag "c6slogo.svg", class: 'logo-img' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

            <li><%= link_to "New LFG Post", new_post_path %></li>
            <li><%= link_to "Posts", root_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon ion-ios-game-controller-b-outline"> </i><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to '<i class="icon ion-ios-gear"></i> Account Settings'.html_safe, edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to '<i class="icon ion-log-out"></i> Logout'.html_safe, destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to '<i class="icon ion-android-arrow-dropup-circle"></i> Sign Up'.html_safe, new_user_registration_path %></li>
              <li><%= link_to '<i class="icon ion-log-in"></i> Login'.html_safe, new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="pull-right user-info">
         <% if current_user.try(:admin?) %>
         <p>Registered Admin</p>
         <% end %>
    </div>
    <br />
    <br />
           <%= yield %>


  <footer><a href="http://rsvision.com">RSVision Development Project 2016</a></footer>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-wrap">
  <div class="row">
      <h1 class="title">About the Cayde-6 Sect Project</h1>
      <p>The Cayde-6 Sect is a Looking For Group application reserved for players in Destiny, Bungie's flagship massive multi-player online video game.</p>
        <h2>How does it work?</h2>
        <p>Go to “New LFG Post” fill out your Console, Gamertag and other info to further your search for likeminded players in the same activity.
        This app is currently in beta for a closed-group of individuals so please request a invite code to checkout the current version <a href="http:/rsvision.com">@RSVision.com</a>!</p>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="lfg-form-container">
  <div class="row">
      <%= form_for @post do |f| %>
        <br />
          <div class="col-xs-6">
          <%= f.label :name, 'Gamertag' %><br />
          <%= f.text_field :name, autofocus: true, placeholder: "Gamertag", :maxlength => 25 %>
          </div>

          <br />

          <div class="col-xs-6">
            <%= f.label :console, 'Select Platform'.html_safe %><br />
            <%= f.select :console, options_for_select([['PS4', 'PS4'],
            ['XB1', 'XB1']]) %>
          </div>
  </div>

        <div class="row">
          <div class="col-xs-6">
            <%= f.label :light_lvl, 'Your Light Level' %><br />
            <%= f.text_field :light_lvl, placeholder: "eg. 335", :maxlength => 3 %>
          </div>

          <br />

          <div class="col-xs-6">
            <%= f.label :activity, 'Select Activity' %><br />
            <%= f.select :activity, options_for_select([
            ['1v1 Private Crucible Match', '1v1 Private Match'],
            ['Private Crucible Match', 'Private Match'],
            ['Rumble', 'Rumble'],
            ['Doubles', 'Doubles'],
            ['Skirmish | Elimination | Salvage', '3v3 Crucible'],
            ['Clash | Control | Rift', '6v6 Crucible'],
            ['Supremecy', 'Supremecy'],
            ['Trials of Osiris: Flawless', 'Trials of Osiris: Flawless'],
            ['Trials of Osiris: Fun', 'Trials of Osiris: Fun'],
            ['Trials of Osiris: Sherpa', 'Trials of Osiris: Sherpa'],
            ['Iron Banner', 'Iron Banner'],
            ['Patrol', 'Patrol'],
            ['Archon\'s Forge', 'Archon\'s Forge'],
            ['Quest', 'Quest'],
            ['Exotic Quest', 'Exotic Quest'],
            ['Strikes Playlist', 'Strikes Playlist'],
            ['Nightfall', 'Nightfall'],
            ['Vault of Glass Raid: Normal', 'Vault of Glass Raid: Normal'],
            ['Vault of Glass Raid: Hard', 'Vault of Glass Raid: Hard'],
            ['Crota\'s End Raid: Normal', 'Crota\'s End Raid: Normal'],
            ['Crota\'s End Raid: Hard', 'Crota\'s End Raid: Hard'],
            ['King\'s Fall Raid: Normal', 'King\'s Fall Raid: Normal'],
            ['King\'s Fall Raid: Hard', 'King\'s Fall Raid: Hard'],
            ['Wrath of the Machine: Normal', 'Wrath of the Machine: Normal'],
            ['Wrath of the Machine: Hard', 'Wrath of the Machine: Hard']
            ]) %>
          </div>
        </div>


        <div class="row">
          <div class="col-xs-6">
            <%= f.label :destiny_class, 'Class' %><br />
            <%= f.select :destiny_class, options_for_select([
              ['Hunter', 'Hunter'],
              ['Warlock', 'Warlock'],
              ['Titan', 'Titan']]) %>
          </div>
        </div>


        <div class="row">
          <div class="form-group notes-wrap">
            <%= f.label :notes %>
            <%= f.text_area :notes, rows: 4, class: 'form-control',
            placeholder: "Enter: Quest Name, Need 2 more players or any other specifics", :maxlength => 35 %>
          </div>

          <br />

          <div class="form-group post-btn-wrap">
            <%= f.submit "Post to LFG!", class: 'btn btn-success' %>
          </div>
        </div>

</div>
<% end %>

app/views/posts/edit.html.erb
<div class="post-wrap">
    <h1><i class="icon ion-ios-game-controller-b"></i> Edit your LFG post:</h1>
    <%= link_to "Delete Post", post_path(@post), method: :delete, class: 'btn btn-danger' %>
    <br />
        <%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class=post-wrap>
  <div class="margin-wrapper">
  <table>
  <%= link_to '<i class="icon ion-ios-compose"></i> Post | Edit LFG'.html_safe, new_post_path, class: 'btn btn-success' %>
  </table>
    <h2><i class="icon ion-ios-game-controller-b"></i> Filter your LFG search</h2>
  </div>
    <br />
      <div class="posts-wrap">
        <table id="postDatatable" class='table display responsive no-wrap' width="100%">
          <thead>
            <tr>
              <th>Console</th>
              <th>Gamertag</th>
              <th>Activity</th>
              <th>Class</th>
              <th>Light</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.console %></td>
                <td><%= post.name %></td>
                <td><%= post.activity %></td>
                <td><%= post.destiny_class %></td>
                <td><%= post.light_lvl %></td>
                <td><%= post.notes %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
</div>
<script>
$(document).ready(function() {
    $('#postDatatable').DataTable( {
      "bLengthChange": false,
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.header()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );

                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );

                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        }
    } );
} );
</script>

app/views/posts/new.html.erb
<div class="post-wrap">
  <h2><i class="icon ion-ios-game-controller-b"></i> New LFG Post</h2>
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="post-wrap">
    <br>
      <div class="posts-wrap">
      <h1>Review Your Post</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Console</th>
            <th>Gamertag</th>
            <th>Activity</th>
            <th>Class</th>
            <th>Light</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @post.console %></td>
            <td><%= @post.name %></td>
            <td><%= @post.activity %></td>
            <td><%= @post.destiny_class %></td>
            <td><%= @post.light_lvl %></td>
            <td><%= @post.notes %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <br />
    <table class="table">
      <%= link_to "Return to All Posts", root_path, class: 'btn btn-lfg' %>
      <%= link_to 'Edit', posts_path(@post), class: 'btn btn-success' %>
      <%= link_to "Delete Post", @post, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    </table>
    <br>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <% unless current_user %>
    <div class="jumbotron no-margin">
      <div class="row no-margin no-padding">
        <h1>The Cayde 6 Sect</h1>
        <p>A Private Destiny LFG Community to bring us together</p>
      </div>
      <div class="row no-margin">
        <div class="col-md-6 no-padding">
          <h2>Not a member?</h2>
          <h4><%= link_to "Create a new account", new_user_registration_path %></h4>
        </div>
        <div class="col-md-6 no-padding">
          <h2>Already have an account?</h2>
          <h4><%= link_to "Sign in", new_user_session_path %></h4>
        </div>
      </div>
    </div>
  <% else %>
    <div class="jumbotron no-margin">
      <div class="row no-margin no-padding">
        <h1>GamingLFG</h1>
        <p>A LFG hub for gaming</p>
      </div>
    </div>
      <div class="row no-margin">
        <div class="col-md-4 pull-left">
          <br />
            <div class="panel panel-primary">
              <div class="panel-heading">
              </div>
              <div class="panel-body">
              </div>
            </div>
        </div>
        <div class="col-md-4">
        <br />
        <div class="panel panel-primary">
          <div class="panel-heading">
          </div>
          <div class="panel-body">
          </div>
        </div>
        </div>
      </div>
  <% end %>
</div>